#!/bin/bash

# Date: 10 de Marco de 2013
# Un script qui syncronise des repertoires distants.

# Attention: pour qu'il me synchronise ce qu'il y a dans le repertoire
# rep1 avec ce qu'il y a dans le repertoire rep2, faut mettre des
# barres a la fin: rsync ... rep1/ ... rep2/ (sinon il copie un des
# repertoires DANS l'autre)

local_dir="/home/sacha/Admin/"
remote_host="sacha@web.mat.ufmg.br"
remote_dir="~/SAUVEGARDES/Admin/"

hora=$(date)

#Atencao: a opcao DELETE apaga tudo que nao ta no local_dir!!! Isso
#pode ser meio ruim se eu quiser fazer a sincronizacao de varios 
#computadores diferentes. 

echo "
--------------------------------------------
Backup: $hora 
-> De $local_dir em $remote_host:
" >> ~/trackingweb1.txt
rsync -avu --rsh=ssh $local_dir $remote_host:$remote_dir >> ~/trackingweb1.txt 
echo "
<- De $remote_host em $local_dir:" >> ~/trackingweb1.txt
rsync -avu --rsh=ssh $remote_host:$remote_dir $local_dir >> ~/trackingweb1.txt
echo "--------------------------------------------
" >> ~/trackingweb1.txt

